defmodule Manfrod.Memory.Conversation do
  @moduledoc """
  A closed conversation session with its summary.

  Conversations are created when the idle timer fires and pending messages
  are processed. The summary is generated by LLM before the conversation
  record is created.
  """
  use Ecto.Schema
  import Ecto.Changeset

  alias Manfrod.Memory.{Message, Node}

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "conversations" do
    field :started_at, :utc_datetime
    field :ended_at, :utc_datetime
    field :summary, :string

    has_many :messages, Message
    has_many :nodes, Node

    timestamps()
  end

  def changeset(conversation, attrs) do
    conversation
    |> cast(attrs, [:started_at, :ended_at, :summary])
    |> validate_required([:started_at, :ended_at, :summary])
  end
end
